"""add additional info for booking

Revision ID: 995c6c936c07
Revises: 99565683b3b2
Create Date: 2024-11-02 21:57:05.497760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '995c6c936c07'
down_revision: Union[str, None] = '99565683b3b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('guest_contact_number', sa.String(), nullable=False))
    op.drop_column('booking', 'guest_contact_numbers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('guest_contact_numbers', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('booking', 'guest_contact_number')
    # ### end Alembic commands ###
